#include <cstdio>
#include <vector>

#include "decoder.hpp"
#include "machine.hpp"
#include "test_util.hpp"

// ---------------------------------------------------------------------------
// The C (compressed) extension.
//
// The interesting half of this suite is a table of encodings produced by the
// **real GNU assembler**, not by anything in this repository. Each row pairs a
// compressed instruction with the 32-bit instruction the specification says it
// is equivalent to, both assembled by `riscv64-unknown-elf-as`. If decompress()
// turns the first into the second, the expansion is right - and it is right
// against an independent implementation, which is the only kind of check worth
// having for a table of hand-transcribed bit positions.
//
// The immediates deliberately include both extremes of each field's range. A
// bit placed in the wrong position often still produces the right answer for
// small values, and only diverges at the top of the range.
// ---------------------------------------------------------------------------

using namespace rvt;

namespace {

struct Case {
    u16         compressed;
    u32         expansion;
    const char* c_asm;
    const char* x_asm;
};

// Generated by assembling each pair with riscv64-unknown-elf-as.
const Case kCases[] = {
    {0x0028, 0x00810513, "c.addi4spn a0, sp, 8", "addi a0, sp, 8"},
    {0x1ffc, 0x3fc10793, "c.addi4spn a5, sp, 1020", "addi a5, sp, 1020"},
    {0x4188, 0x0005a503, "c.lw a0, 0(a1)", "lw a0, 0(a1)"},
    {0x5ef8, 0x07c6a703, "c.lw a4, 124(a3)", "lw a4, 124(a3)"},
    {0x6188, 0x0005b503, "c.ld a0, 0(a1)", "ld a0, 0(a1)"},
    {0x7ef8, 0x0f86b703, "c.ld a4, 248(a3)", "ld a4, 248(a3)"},
    {0xc1c8, 0x00a5a223, "c.sw a0, 4(a1)", "sw a0, 4(a1)"},
    {0xe588, 0x00a5b423, "c.sd a0, 8(a1)", "sd a0, 8(a1)"},
    {0x0001, 0x00000013, "c.nop", "addi x0, x0, 0"},
    {0x0505, 0x00150513, "c.addi a0, 1", "addi a0, a0, 1"},
    {0x1501, 0xfe050513, "c.addi a0, -32", "addi a0, a0, -32"},
    {0x2505, 0x0015051b, "c.addiw a0, 1", "addiw a0, a0, 1"},
    {0x3481, 0xfe04849b, "c.addiw s1, -32", "addiw s1, s1, -32"},
    {0x457d, 0x01f00513, "c.li a0, 31", "addi a0, x0, 31"},
    {0x5501, 0xfe000513, "c.li a0, -32", "addi a0, x0, -32"},
    {0x6141, 0x01010113, "c.addi16sp sp, 16", "addi sp, sp, 16"},
    {0x7101, 0xe0010113, "c.addi16sp sp, -512", "addi sp, sp, -512"},
    {0x6505, 0x00001537, "c.lui a0, 1", "lui a0, 1"},
    {0x757d, 0xfffff537, "c.lui a0, 0xfffff", "lui a0, 0xfffff"},
    {0x8105, 0x00155513, "c.srli a0, 1", "srli a0, a0, 1"},
    {0x917d, 0x03f55513, "c.srli a0, 63", "srli a0, a0, 63"},
    {0x9501, 0x42055513, "c.srai a0, 32", "srai a0, a0, 32"},
    {0x997d, 0xfff57513, "c.andi a0, -1", "andi a0, a0, -1"},
    {0x893d, 0x00f57513, "c.andi a0, 15", "andi a0, a0, 15"},
    {0x8d0d, 0x40b50533, "c.sub a0, a1", "sub a0, a0, a1"},
    {0x8d2d, 0x00b54533, "c.xor a0, a1", "xor a0, a0, a1"},
    {0x8d4d, 0x00b56533, "c.or a0, a1", "or a0, a0, a1"},
    {0x8d6d, 0x00b57533, "c.and a0, a1", "and a0, a0, a1"},
    {0x9d0d, 0x40b5053b, "c.subw a0, a1", "subw a0, a0, a1"},
    {0x9d2d, 0x00b5053b, "c.addw a0, a1", "addw a0, a0, a1"},
    {0x0506, 0x00151513, "c.slli a0, 1", "slli a0, a0, 1"},
    {0x157e, 0x03f51513, "c.slli a0, 63", "slli a0, a0, 63"},
    {0x4502, 0x00012503, "c.lwsp a0, 0(sp)", "lw a0, 0(sp)"},
    {0x557e, 0x0fc12503, "c.lwsp a0, 252(sp)", "lw a0, 252(sp)"},
    {0x6502, 0x00013503, "c.ldsp a0, 0(sp)", "ld a0, 0(sp)"},
    {0x757e, 0x1f813503, "c.ldsp a0, 504(sp)", "ld a0, 504(sp)"},
    {0xc02a, 0x00a12023, "c.swsp a0, 0(sp)", "sw a0, 0(sp)"},
    {0xdfaa, 0x0ea12e23, "c.swsp a0, 252(sp)", "sw a0, 252(sp)"},
    {0xe02a, 0x00a13023, "c.sdsp a0, 0(sp)", "sd a0, 0(sp)"},
    {0xffaa, 0x1ea13c23, "c.sdsp a0, 504(sp)", "sd a0, 504(sp)"},
    {0x8502, 0x00050067, "c.jr a0", "jalr x0, 0(a0)"},
    {0x9502, 0x000500e7, "c.jalr a0", "jalr x1, 0(a0)"},
    {0x852e, 0x00b00533, "c.mv a0, a1", "add a0, x0, a1"},
    {0x952e, 0x00b50533, "c.add a0, a1", "add a0, a0, a1"},
    {0x9002, 0x00100073, "c.ebreak", "ebreak"},
    {0xa011, 0x0040006f, "c.j +4", "jal x0, 1b+4"},
    {0xbff5, 0xffdff06f, "c.j -4", "jal x0, 1b+-4"},
    {0xaffd, 0x7fe0006f, "c.j +2046", "jal x0, 1b+2046"},
    {0xb001, 0x801ff06f, "c.j -2048", "jal x0, 1b+-2048"},
    {0xc111, 0x00050263, "c.beqz +4", "beq a0, x0, 1b+4"},
    {0xdd75, 0xfe050ee3, "c.beqz -4", "beq a0, x0, 1b+-4"},
    {0xcd7d, 0x0e050f63, "c.beqz +254", "beq a0, x0, 1b+254"},
    {0xd101, 0xf00500e3, "c.beqz -256", "beq a0, x0, 1b+-256"},
    {0xe111, 0x00051263, "c.bnez +4", "bne a0, x0, 1b+4"},
    {0xfd75, 0xfe051ee3, "c.bnez -4", "bne a0, x0, 1b+-4"},
    {0xed7d, 0x0e051f63, "c.bnez +254", "bne a0, x0, 1b+254"},
    {0xf101, 0xf00510e3, "c.bnez -256", "bne a0, x0, 1b+-256"},
};

void test_expansions_match_the_assembler() {
    for (const Case& c : kCases) {
        const u32 got = decompress(c.compressed);
        if (got != c.expansion) {
            ++testutil::g_checks;
            char msg[256];
            std::snprintf(msg, sizeof msg,
                          "%s -> got 0x%08x, expected 0x%08x (%s)",
                          c.c_asm, got, c.expansion, c.x_asm);
            testutil::report_failure(__FILE__, __LINE__, msg);
        } else {
            ++testutil::g_checks;
        }
    }
}

void test_illegal_encodings_expand_to_zero() {
    // Zero is permanently illegal in RISC-V, deliberately, so that a jump into
    // zeroed memory faults at once rather than running through it. decompress()
    // reuses that: an encoding with no meaning expands to zero and the normal
    // illegal-instruction path takes over.
    CHECK(decompress(0x0000) == 0);          // the all-zero halfword
    CHECK(decompress(0x0002) == 0);          // C.ADDI4SPN with nzuimm == 0
    CHECK(decompress(0x6001) == 0);          // C.LUI with rd == x0
    CHECK(decompress(0x6101) == 0);          // C.LUI with a zero immediate
    CHECK(decompress(0x2001) == 0);          // C.ADDIW with rd == x0
    CHECK(decompress(0x9c61) == 0);          // reserved MISC-ALU encoding
    CHECK(decompress(0x8002) == 0);          // C.JR with rs1 == x0
    CHECK(decompress(0x0002 | (0 << 7)) == 0);
}

void test_float_encodings_are_illegal_until_f_and_d_land() {
    // C.FLD / C.FSD / C.FLDSP / C.FSDSP are valid compressed instructions, but
    // they need the D extension, which this phase does not implement. They must
    // trap rather than being expanded into something that happens to decode.
    CHECK(decompress(0x2188) == 0);   // c.fld  fa0, 0(a1)
    CHECK(decompress(0xa188) == 0);   // c.fsd  fa0, 0(a1)
    CHECK(decompress(0x2102) == 0);   // c.fldsp fa0, 0(sp)
    CHECK(decompress(0xa002) == 0);   // c.fsdsp fa0, 0(sp)
}

void test_instruction_length_is_read_from_the_low_bits() {
    // RISC-V marks length in the low two bits: 11 means 32 bits or wider,
    // anything else means a 16-bit compressed instruction. This is what lets
    // the two lengths be mixed freely with no mode bit anywhere.
    CHECK(!is_32bit_instruction(0x0028));   // c.addi4spn
    CHECK(!is_32bit_instruction(0x4188));   // c.lw
    CHECK(!is_32bit_instruction(0x0001));   // c.nop
    CHECK(is_32bit_instruction(0x0513));    // low half of addi a0, sp, 8
    CHECK(is_32bit_instruction(0xffff));
}

void test_decode16_reports_length_and_original_encoding() {
    // A compressed instruction decodes as its expansion, so every execute path
    // sees one uniform 32-bit encoding - but `encoded` and `length` remember
    // what the program actually contained. mtval and the tracer need that:
    // reporting the expansion would name an instruction that is not there.
    const DecodedInst c = decode16(0x0028, 0);          // c.addi4spn a0, sp, 8
    CHECK_EQ_U(c.raw, 0x00810513);
    CHECK_EQ_U(c.encoded, 0x0028);
    CHECK_EQ_U(c.length, 2);
    CHECK(c.opcode == opcodes::OP_IMM);
    CHECK_EQ_U(c.rd, 10);
    CHECK_EQ_U(c.imm, 8);

    const DecodedInst full = decode16(0x0513, 0x0081); // addi a0, sp, 8
    CHECK_EQ_U(full.raw, 0x00810513);
    CHECK_EQ_U(full.encoded, 0x00810513);
    CHECK_EQ_U(full.length, 4);
}

// --- executing compressed code ----------------------------------------------

// Lay out a program of raw halfwords in DRAM and run it. The Machine helper
// takes 32-bit words, so mixed-width programs are assembled by hand here.
Machine machine_from_halfwords(const std::vector<u16>& halves) {
    std::vector<u32> words;
    for (std::size_t i = 0; i < halves.size(); i += 2) {
        const u32 low  = halves[i];
        const u32 high = (i + 1 < halves.size()) ? halves[i + 1] : 0;
        words.push_back((high << 16) | low);
    }
    return Machine(words);
}

void test_compressed_program_executes_and_advances_two_bytes() {
    // c.li a0, 5 ; c.li a1, 7 ; c.add a0, a1
    Machine m = machine_from_halfwords({0x4515, 0x459d, 0x952e});
    CHECK(m.cpu->run(3, nullptr));
    CHECK_EQ_U(m.reg(10), 12);
    // Three 2-byte instructions: the PC advanced by six, not twelve.
    CHECK_EQ_U(m.cpu->pc, DRAM_BASE + 6);
}

void test_compressed_and_full_width_instructions_interleave() {
    // c.li a0, 1 ; addi a0, a0, 10 (32-bit) ; c.addi a0, 1
    std::vector<u16> halves = {0x4505};
    const u32 addi = ADDI(10, 10, 10);
    halves.push_back(static_cast<u16>(addi & 0xffff));
    halves.push_back(static_cast<u16>(addi >> 16));
    halves.push_back(0x0505);

    Machine m = machine_from_halfwords(halves);
    CHECK(m.cpu->run(3, nullptr));
    CHECK_EQ_U(m.reg(10), 12);
    CHECK_EQ_U(m.cpu->pc, DRAM_BASE + 8);   // 2 + 4 + 2
}

void test_compressed_branch_displacement() {
    //   c.li   a0, 0
    //   c.beqz a0, 2f     <- taken
    //   c.li   a0, 9      <- skipped
    // 2: c.li  a0, 21
    // Assembled by riscv64-unknown-elf-as, so the displacement is the real one
    // rather than one this repository computed for itself.
    Machine m = machine_from_halfwords({0x4501, 0xc111, 0x4525, 0x4555});
    CHECK(m.cpu->run(3, nullptr));
    CHECK_EQ_U(m.reg(10), 21);
    // Two instructions ran and the branch skipped a third: 2 + 2 + 2.
    CHECK_EQ_U(m.cpu->pc, DRAM_BASE + 8);
}

void test_compressed_jump() {
    //   c.j   2f
    //   c.li  a1, 9       <- skipped
    // 2: c.li a1, 7
    Machine m = machine_from_halfwords({0xa011, 0x45a5, 0x459d});
    CHECK(m.cpu->run(2, nullptr));
    CHECK_EQ_U(m.reg(11), 7);
    // C.J expands to `jal x0, offset`, so nothing was linked.
    CHECK_EQ_U(m.reg(1), 0);
}

void test_illegal_compressed_instruction_reports_its_own_bits() {
    // mtval must hold what was in memory - the 16-bit halfword - not the
    // 32-bit expansion, which for an illegal encoding does not exist anyway.
    Machine m = machine_from_halfwords({0x0000});
    const Status st = m.cpu->step();
    CHECK(!st);
    CHECK(st.trap.cause == Exception::IllegalInstruction);
    CHECK_EQ_U(st.trap.tval, 0);

    Machine m2 = machine_from_halfwords({0x6001});   // c.lui with rd = x0
    const Status st2 = m2.cpu->step();
    CHECK(!st2);
    CHECK(st2.trap.cause == Exception::IllegalInstruction);
    CHECK_EQ_U(st2.trap.tval, 0x6001);
}

}  // namespace

int main() {
    test_expansions_match_the_assembler();
    test_illegal_encodings_expand_to_zero();
    test_float_encodings_are_illegal_until_f_and_d_land();
    test_instruction_length_is_read_from_the_low_bits();
    test_decode16_reports_length_and_original_encoding();
    test_compressed_program_executes_and_advances_two_bytes();
    test_compressed_and_full_width_instructions_interleave();
    test_compressed_branch_displacement();
    test_compressed_jump();
    test_illegal_compressed_instruction_reports_its_own_bits();
    return testutil::summary("compressed");
}
